# The URL the site will be built for
base_url = "https://rachitnigam.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[link_checker]
skip_prefixes = [
  "https://twitter.com/",
]

[extra]
news_items = 5

# Links to author webpages
author = [
  { name = "Griffin Berlstein", link = "https://griffinberlste.in/" },
  { name = "Chris Gyurgyik", link = "https://cgyurgyik.github.io/" },
  { name = "Vincent Lee", link = "https://www.linkedin.com/in/vincent-lee-15685425" },
  { name = "Alexa VanHattum", link = "https://www.cs.cornell.edu/~avh/" },
  { name = "James Bornholt", link = "https://www.cs.utexas.edu/~bornholt/" },
  { name = "Samuel Thomas", link = "https://sgtpeacock.com/" },
  { name = "Zhijing Li", link = "https://tissue3.github.io/" },
  { name = "Ted Bauer", link = "https://tedbauer.github.io/" },
  { name = "Adrian Sampson", link = "http://adriansampson.net" },
  { name = "Zhiru Zhang", link = "http://www.csl.cornell.edu/~zhiruz/" },
  { name = "Arjun Guha", link = "https://ccs.neu.edu/~arjunguha/main/home/" },
  { name = "Sam Baxter", link = "https://baxtersa.github.io/about/" },
  { name = "Shriram Krishnamurthi", link = "http://cs.brown.edu/~sk/" },
  { name = "Joe Gibbs Politz", link = "https://jpolitz.github.io/" },
  { name = "Jean-Baptiste Jeannin", link = "https://jeannin.github.io/" },
  { name = "Yuwei Ye", link = "https://www.viviyye.com/" },
  { name = "Sachille Atapattu", link = "https://www.csl.cornell.edu/~sachille/"},
  { name = "Jane Tangen", link = "https://people.cs.umass.edu/~jktangen/" }
]
